-- liquibase formatted sql
-- changeset demoprojyan:001.1
CREATE TABLE exampletab1 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100),
    CONSTRAINT "exampletab1PK" PRIMARY KEY (id)
);
-- rollback DROP TABLE exampletab1